### ISSUE TITLE
Why there are no stars

### ISSUE THREAD

**Issue by ugintl** [enessfk/TheHouseSteak#1]
This will be my first time installing a python django app. Looks very attractive, but I am wondering why there are no stars on this project. This app deserves some stars. Is it a new project?

**Comment by enessfk** [comment]
Yes, it's actually a project I've developed before, but I just shared it on
github. I uploaded it to Github 1-2 weeks ago. If you like it, you can give
the first star. If there is any question about the project, I will be happy
to answer it. Yours sincerely!.

**Comment by ugintl** [comment]
Thanks. I will definitely try it and let you know if I have any questions.

I am on windows 10. I have python 2.7 installed. Whereas, Your project requires python 3. Can I use 2 different python versions at the same time?

**Comment by enessfk** [comment]
Of course, you can use two different versions of Python at the same time. Virtual Environments can have both a specific version of Python and of any project-specific packages installed within them, without affecting any other projects. You can find the detailed explanation in the links : 
- [installing-multiple-python-versions-on-windows-using-virtualenv](https://www.freecodecamp.org/news/installing-multiple-python-versions-on-windows-using-virtualenv/)
- [manage-multiple-python-versions-and-virtual-environments](https://www.freecodecamp.org/news/manage-multiple-python-versions-and-virtual-environments-venv-pyenv-pyvenv-a29fb00c296f/)

I hope it helps.

**Comment by ugintl** [comment]
Thanks. If I want to upload it to a hosting, what should I be looking in that hosting? What are the server requirements? 

For example, when I want to host a normal php app, I am looking for apache/nginx, php and mysql support. In short a lamp stack.
